require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AwesomePhotoviewExample' do
  config = use_native_modules!


  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-awesome-photoview', :path => '../..'
#  pod 'Lantern'
#  pod 'SDWebImage'
  pod 'YBImageBrowser', :git => 'https://github.com/web3miaomiao/YBImageBrowser.git'
  pod 'YBImageBrowser/Video', :git => 'https://github.com/web3miaomiao/YBImageBrowser.git'
  pod 'YYImage', :git => 'https://github.com/web3miaomiao/YYImage.git'


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.102.0' })
  use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})

  post_install do |installer|
    flipper_post_install(installer)
  end
end
